"""Populate Plans

Revision ID: 3bce90c96a6a
Revises: 811554982f66
Create Date: 2025-01-04 15:59:35.955135

"""
from typing import Sequence, Union
from app.helpers.data import plans
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bce90c96a6a'
down_revision: Union[str, None] = '811554982f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def data_upgrades():
    plan = sa.sql.table("plans", sa.sql.column('id', sa.String))

    op.bulk_insert(plan, list(map(lambda x: {'id': x}, list(set(plans.split('\n'))))))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    data_upgrades()
    # ### end Alembic commands ###


def data_drop():
    op.execute("DELETE FROM plans")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    data_drop()
    # ### end Alembic commands ###
