"""Added Plan and ChangePlan models

Revision ID: 811554982f66
Revises: 266183bb48a0
Create Date: 2025-01-04 15:58:23.653185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811554982f66'
down_revision: Union[str, None] = '266183bb48a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('changed_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changed_plans_id'), 'changed_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changed_plans_id'), table_name='changed_plans')
    op.drop_table('changed_plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
