"""Populate auditories

Revision ID: fa5a0267aace
Revises: ca63b3dbe208
Create Date: 2025-01-03 16:43:56.184121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.helpers.data import auds

# revision identifiers, used by Alembic.
revision: str = 'fa5a0267aace'
down_revision: Union[str, None] = 'ca63b3dbe208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def data_upgrades():
    auditories = sa.sql.table("auditories", sa.sql.column('id', sa.String))

    op.bulk_insert(auditories, list(map(lambda x: {'id': x}, list(set(auds.split('\n'))))))


def data_drop():
    op.execute("DELETE FROM auditories")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    data_upgrades()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    data_drop()
    # ### end Alembic commands ###
